services:
  - type: web
    name: Test-Generator-Frontend
    env: static
    staticPublishPath: /frontend/build
    buildCommand: npm install && npm run build
    branch: main

  - type: web
    name: Test-Generator-Backend
    env: node
    startCommand: node server.js
    buildCommand: npm install
    branch: main
