import { createContext, useState } from "react";

export const GlobalContext = createContext(null);

function Context({ children }) {
  const refreshToken = localStorage.getItem("refreshToken");
  const [isAuthenticated, setIsAuthenticated] = useState(
    refreshToken ? true : null
  );
  const [accessToken, setAccessToken] = useState("");

  const [questionsTestNum, setQuestionsTestNum] = useState(0); // State for the number of questions in the test
  const [testTitle, setTestTitle] = useState(""); // Manual Category
  const [manualTestDifficulty, setManualTestDifficulty] = useState("easy"); // Manual Difficulty
  const [userAnswers, setUserAnswers] = useState([]); // State to store user's answers to the test

  const [testsData, setTestsData] = useState([]); // State to store all test data retrieved from the API
  const [category, setCategory] = useState("");
  const [difficulty, setDifficulty] = useState("easy");
  const [limit, setLimit] = useState(""); // Number of questions generated by API in a test

  const [loading, setLoading] = useState(false);

  const fetchUserTests = async () => {
    setLoading(true);
    try {
      const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/tests/fetchtests`, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      const data = await response.json();
      if (response.ok) {
        setTestsData(data.tests);
        setLoading(false);
      } else {
        console.error("Failed to fetch user data:", data.message);
      }
    } catch (error) {
      console.error("Error fetching user data:", error.message);
    }
  };

  const saveTest = async (testData, manualTest = false) => {
    try {
      const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/tests/save`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify({ testData, manualTest }),
      });
      const data = await response.json();
      if (response.status === 201) {
        setTestsData((prevTests) => [...prevTests, data.savedTest]);
      } else {
        console.log(response);
      }
    } catch (error) {
      console.error("Error saving test:", error.message);
    }
  };

  // Function to fetch test questions from the Open Trivia Database API
  const handleSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    try {
      const res = await fetch(
        `https://opentdb.com/api.php?amount=${limit}&category=${category}&difficulty=${difficulty}&type=multiple`
      );
      const data = await res.json();

      // If data is successfully fetched and results are available
      if (Array.isArray(data.results) && data.results.length > 0) {
        // Map the fetched questions to match the schema
        const testData = data.results.map((item) => ({
          category: item.category,
          question: item.question,
          correct_answer: item.correct_answer,
          incorrect_answers: item.incorrect_answers,
          difficulty: item.difficulty,
        }));
        await saveTest(testData);
        setLimit("");
        setLoading(false);
      }
    } catch (error) {
      console.log(error);
      setLoading(false);
    }
  };

  return (
    <GlobalContext.Provider
      value={{
        accessToken,
        setAccessToken,
        questionsTestNum,
        setQuestionsTestNum,
        testTitle,
        setTestTitle,
        manualTestDifficulty,
        setManualTestDifficulty,
        userAnswers,
        setUserAnswers,
        handleSubmit,
        category,
        setCategory,
        difficulty,
        setDifficulty,
        limit,
        setLimit,
        testsData,
        setTestsData,
        loading,
        setLoading,
        isAuthenticated,
        setIsAuthenticated,
        saveTest,
        fetchUserTests,
      }}
    >
      {children}
    </GlobalContext.Provider>
  );
}

export default Context;
